site_name: kubed-sh
site_description: 'A cloud native shell for Kubernetes'
site_author: 'Michael Hausenblas'
repo_name: 'mhausenblas/kubed-sh'
repo_url: 'https://github.com/mhausenblas/kubed-sh'
copyright: 'Copyright &copy; 2020 Amazon'
nav:
    - Home: index.md
    - Install: install.md
    - Use: use.md
    - FAQ: faq.md
    - Background:
        - Motivation: motivation.md
        - Design: design.md
        - Use Cases: usecases.md
theme:
    name: 'material'
    favicon: 'img/favicon.ico'
    logo: 'img/favicon.ico'
    font:
      text: 'Lato'
      code: 'PT Mono'
    palette:
      primary: 'blue grey'
      accent: 'orange'
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true
    - pymdownx.details
    - pymdownx.superfences

